---
title: "map_Rcode"
author: "Yuhong Guo"
date: "16/08/2021"
output: html_document
---

Load libraries
```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(sf)
library(curl)
library(ggmap)
library(tmap)
library(tmaptools)
library(feather)
```

```{r}
df = read.csv("../preprocessed_data/df_small.csv",stringsAsFactors = TRUE)
```

```{r}
library(sf)
```

```{r}
sf = st_read("../raw_data/taxi_zones/taxi_zones.shp")
zone = read.csv("../raw_data/taxi_zones/taxi+_zone_lookup.csv")
```

Basic information in shapefile.

```{r message=FALSE, warning=FALSE, fig.align = "center"}
sf = st_read("../raw_data/taxi_zones/.")
plot(sf)
```

```{r}
df %>% 
  group_by(PULocationID) %>% 
  summarise(n = n()) -> df_summary1
```
```{r}
sf_join <- 
left_join(sf,df_summary1,
          by=c("LocationID"="PULocationID")) 
```
```{r message=FALSE, warning=FALSE, fig.align = "center"}
tm_shape(sf_join)+
   tm_polygons('n',style="pretty")
```

```{r}
df %>% 
  group_by(PULocationID) %>% 
  summarise(total_mean = mean(total_amount)) -> df_summary2
```
```{r}
sf_join <- 
left_join(sf,df_summary2,
          by=c("LocationID"="PULocationID")) 
```
```{r message=FALSE, warning=FALSE, fig.align = "center"}
tm_shape(sf_join)+
   tm_polygons('total_mean',style="pretty")
```

```{r}
df %>% 
  group_by(PULocationID) %>% 
  summarise(distance_mean = mean(trip_distance)) -> df_summary3
```
```{r}
sf_join <- 
left_join(sf,df_summary3,
          by=c("LocationID"="PULocationID")) 
```
```{r message=FALSE, warning=FALSE, fig.align = "center"}
tm_shape(sf_join)+
   tm_polygons('distance_mean',style="pretty")
```

```{r}
df %>% 
  group_by(PULocationID) %>% 
  summarise(tip_mean = mean(tip_amount)) -> df_summary4
```
```{r}
sf_join <- 
left_join(sf,df_summary4,
          by=c("LocationID"="PULocationID")) 
```
```{r message=FALSE, warning=FALSE, fig.align = "center"}
tm_shape(sf_join)+
   tm_polygons('tip_mean',style="pretty")
```
